name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Her gün saat 00:00'da çalışacak
  workflow_dispatch: # Manuel tetikleme için

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: 'batuhanyalin'  # Buraya kendi kullanıcı adını yaz
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
